function myZero = P_tilde(P_, x, Pi, Pj, Hij, Lij, T)

% Model constants
b = -1;
alpha1 = 4;
beta = 0.4;
alpha0 = 64 / (3 * pi * (1 - 4 / b));
alpha = @(p1, p2, h) (alpha0 * (2 / pi) *...
    atan(alpha1 * getKnudsen(((p1 + p2) / 2), h, T)^beta));
sigma = 1;

Pij_ = Pi / Pj;
B = Pij_^2 - 1 + 2 * (6 + alpha(Pi, Pj, Hij)) * (2 - sigma) / sigma *...
    getKnudsen(Pj, Hij, T) * (Pij_ - 1) + 2 * (6 * b +...
    alpha(Pi, Pj, Hij)) * (2 - sigma) / sigma *...
    getKnudsen(Pj, Hij, T)^2 * log((Pij_ - b * getKnudsen(Pj, Hij, T)) /...
    (1 - b * getKnudsen(Pj, Hij, T)));

myZero = P_^2 - 1 + 2 * (6 + alpha(Pi, Pj, Hij)) * (2 - sigma) / sigma *...
    getKnudsen(Pj, Hij, T) * (P_ - 1) + 2 * (6 * b +...
    alpha(Pi, Pj, Hij)) * (2 - sigma) / sigma *...
    getKnudsen(Pj, Hij, T)^2 * log((P_ - b * getKnudsen(Pj, Hij, T)) /...
    (1 - b * getKnudsen(Pj, Hij, T))) - B * (1 - x / Lij);

end